# Generated by Django 4.2.4 on 2023-09-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity_ordered', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('quantity_sold', models.IntegerField()),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
