# Generated by Django 4.2.4 on 2023-09-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_id',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
