---
apiVersion: v1
kind: Service
metadata:
  name: db-warehouse
spec:
  selector:
    app: db-warehouse
  ports:
  - protocol: TCP
    port: 5431
    targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-warehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-warehouse   # Corrected this to match the template labels
  template:
    metadata:
      labels:
        app: db-warehouse
    spec:
      containers:
      - name: db-warehouse
        image: postgres:14.0-alpine
        env:
        # Note: The environment variables should be stored in Secrets or ConfigMaps for better security.
        - name: POSTGRES_DB
          value: db_warehouse
        - name: POSTGRES_USER
          value: test
        - name: POSTGRES_PASSWORD
          value: test
        ports:
        - containerPort: 5432

---
# Remember to repeat the above structure for db_accounts and db_sales

---
apiVersion: v1
kind: Service
metadata:
  name: warehouse
spec:
  selector:
    app: warehouse
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouse   # This was already correct
  template:
    metadata:
      labels:
        app: warehouse
    spec:
      containers:
      - name: warehouse
        image: brewunifiedapi-warehouse:latest
        env:
        # Note: The environment variables should be stored in Secrets or ConfigMaps for better security.
        - name: DB_USER
          value: test
        - name: DB_PASSWORD
          value: test
        # ... Add other environment variables as needed ...
        command: ["./wait-for-it.sh", "redis:6379", "--", "python", "manage.py", "runserver", "0.0.0.0:8001"]
        ports:
        - containerPort: 8001
