# Generated by Django 4.2.4 on 2023-09-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounting_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(
                choices=[('Admin', 'Admin'), ('User', 'User')], default='User',
                max_length=50),
        ),
    ]
