name: CD to CloudSigma VM

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to CloudSigma VM
      env:
        SSHPASS: ${{ secrets.VM_SSH_PASSWORD }}
      run: |
        # Install SSH client and sshpass
        sudo apt-get install -y ssh sshpass

        # Copy code to VM using rsync and sshpass
        sshpass -e rsync -e "ssh -o StrictHostKeyChecking=no" -av ./ cloudsigma@31.171.241.189:./BrewUnifiedAPI/

        # Optional: Run any post-deployment commands using sshpass, e.g., restarting services
        sshpass -e ssh -o StrictHostKeyChecking=no cloudsigma@31.171.241.189 "cd /home/cloudsigma/BrewUnifiedAPI && make serve"
