name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8, 3.9 ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Test Sales Service
      - name: Install Sales Dependencies
        working-directory: ./services/sales
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Sales Tests
        working-directory: ./services/sales
        env:
          DJANGO_SETTINGS_MODULE: sales.test_settings
        run: |
          python manage.py test
      

      # Test Warehouse Service
      - name: Install Warehouse Dependencies
        working-directory: ./services/warehouse
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Warehouse Tests
        working-directory: ./services/warehouse
        env:
          DJANGO_SETTINGS_MODULE: warehouse.test_settings
        run: |
          python manage.py test

      # Test Accounting Service
      - name: Install Accounting Dependencies
        working-directory: ./services/accounting
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Accounting Tests
        working-directory: ./services/accounting
        env:
          DJANGO_SETTINGS_MODULE: accounting.test_settings
        run: |
          python manage.py test
